version: '3'
services:
  agi-frontpage-web:
    container_name: agi-frontpage-web-app
    image:  ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3033:80'
    networks:
      - avrist-network
networks:
  avrist-network:
    driver: 'bridge'
